### ISSUE TITLE
Some corrupted lockfile

### ISSUE THREAD

**Issue by bijianing97** [NomicFoundation/hardhat-vscode#272]
Sometime I use the vscode and hardhat solidity I get following error
![image](https://user-images.githubusercontent.com/28391927/197441389-2e7d0c6a-ac25-4663-a990-3a11d2397cfd.png)

How can I solve it?
vscode version 1.72.2
hardhat solidity 0.5.5

**Comment by kanej** [comment]
Hey @bijianing97,

This is an issue with hardhat. If you run `npx hardhat compile` at the command line for this project you will see the error more clearly.

It is happening because of a dependency of hardhat that is platform specific. In your lockfile (`package-lock.json` for npm) you have a different platform version of the dependency that will run on your platform (maybe your running on mac, but the dep was checked in on windows).

This is a known issue, the workaround is:

1. Delete your lockfile (`package-lock.json` for npm)
2. Delete your `node_modules` folder
3. Reinstall with `npm install`

**Comment by bijianing97** [comment]
Thanks sir, now I can code with  it correctly.

**Comment by alcuadrado** [comment]
For the record: https://github.com/npm/cli/issues/4828
