### ISSUE TITLE
bug: foundry / hh hybrid project doesn't index correctly on Linux

### ISSUE THREAD

**Issue by elmariachi111** [NomicFoundation/hardhat-vscode#365]
When you mix hardhat & foundry into one project (e.g. to create advanced, JS backed test cases) , the plugin fails to index the dependency files correctly.  Here's our "internal" discussion on this issue: https://github.com/moleculeprotocol/IPNFT/pull/51 (contains screenshots)

Setup
- we're having a `hardhat.config.js` and a `forge.toml` side by side in the same project
- Foundry is in the lead (all dependencies are submodules in lib)
- We added the recommended remapping preprocessor on the hardhat config, so hardhat is able to compile the project (`yarn hardhat compile` & `forge b` both work)

Action
- when we disable Juan's Solidity extension and enable the hh-vsc extension instead and reload vsc, this is the extension's output: 

![image](https://user-images.githubusercontent.com/1344649/211374419-e61ff9ad-eec6-48c0-9991-e6957498ecd2.png)

Effect
- we can't "click on a parent / dependency file", the dependency seems to not be resolved:

![image](https://user-images.githubusercontent.com/1344649/211275419-7eda77a8-0929-4d0c-a2b9-bee70ffc9794.png)

Sidenote: this seems to work fine on macOS but not on Linux :thinking: 

To manually "hack" it to work on Linux, we're 
- deleting the hardhat file
- restart the ide
- potentially save the `remappings` file to trigger an index
- now it works on Linux (but hardhat doesn't work anymore ;) )

**Comment by antico5** [comment]
Hey @elmariachi111 ! thanks for reporting this. 

What is happening is that our extension is identifying two different projects with the same root and contracts folder (i.e. both `foundry.toml` and `hardhat.config.js` are on the same folder, and they both have their contracts folder to be `src`). The model we have on our server allows for only one project to be associated to a file, because that project is in charge of providing a way to compile the given contract. Since there are 2 candidates, hardhat is arbitrarily taking precedence. That means that the hardhat project is in charge of building the input for solc, and a part of that is resolving imports. In theory dependencies should be resolved correctly because the `hardhat-preprocessor` plugin mutates the code before it reaches the dependency resolution step, but when using the extension, we override the `TASK_COMPILE_SOLIDITY_READ_FILE` task to read files from the editor buffer instead of disk (same task that `hardhat-preprocessor` is overriding). That's why compilation  fails on the extension and you get a diagnostic with an invalid import message.

The errors about failing to load HRE on dependencies (e.g. openzeppelin contracts) can be ignored. It's being indexed as an independent hardhat project becuase it's not inside a node_modules folder.

The proposed solution is to wait until the next hardhat release (likely tomorrow) when we will also release a hardhat plugin called `hardhat-foundry`, which gives better support for your use case without having to use the preprocessor plugin, and works naturally with the extension, since the method for applying remappings is different.

Stay tuned in twitter and discord for the next release, as a tutorial will also be included on how to use the new plugin.

**Comment by elmariachi111** [comment]
That’s such a lovely answer, thanks a lot for taking the time to provide these insights, we’re happy to check out the release as soon as it’s landed :)

**Comment by fvictorio** [comment]
@elmariachi111 we just published the plugin :slightly_smiling_face: You can learn how to use it [here](https://hardhat.org/hardhat-runner/docs/advanced/hardhat-and-foundry).

**Comment by kanej** [comment]
@elmariachi111 let us know if there is anything we can do (or any bug reports) to let you leverage the extension in your repo.

**Comment by antico5** [comment]
> > @elmariachi111 let us know if there is anything we can do (or any bug reports) to let you leverage the extension in your repo.
> 
> hey @kanej . We added the plugin to our project and removed our custom remappings and overrides -> https://github.com/moleculeprotocol/IPNFT/pull/54/files
> 
> When I do a `yarn hardhat compile` this yields `The library @openzeppelin/contracts-upgradeable, imported from src/IPNFT.sol, is not installed.`
> 
> Libraries are installed of course (`forge b` works).
> 
> Seems the plugin isn't picking up the `remappings.txt` in our case thinking
> 
> Checked out the default foundry.toml that's created by your init command that sets foundry's source path to `contracts` but that's not foundry's default (and we'd prefer to leave it as it is)
> 
> ![image](https://user-images.githubusercontent.com/1344649/213499533-8e7b335e-3e06-4460-b20d-43d0079cfff7.png)

The `foundry.toml` file generated by the extension is only for projects that want to add foundry on top of hardhat. That's why the contracts folder is set to be the one that hardhat uses. But for adding hardhat on an existing foundry codebase, it doesn't generate the toml file, it just sets up hardhat to use foundry's folders (src and lib by default).

I'll take a look now to see why the missing library error could be happening

**Comment by antico5** [comment]
@elmariachi111 I found the issue, you need to use hardhat `>=2.12.6` for the plugin to work. I pushed a sample PR with the setup I tested with locally. Both hardhat and the extension worked nicely: https://github.com/moleculeprotocol/IPNFT/pull/55

**Comment by elmariachi111** [comment]
ah great, this wasn't updated on my box. After restarting my IDE even the plugin starts working, thanks for the headsup :)
