### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by LingCoder** [NomicFoundation/hardhat-vscode#412]
After I installed the Solidity plugin from the vscode marketplace, it cannot prompt syntax errors of sol files during use. I uninstalled all other plugins related to solidity, but the result is still the same: syntax prompting does not work.

When I opened the plugin page, I saw an uncaught error message: Language client is not ready yet.

VS Code Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
DateTime: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
SandBox: No

Solidity version v0.6.11
OS : Window 11

**Comment by kanej** [comment]
Hello @LingCoder, by 'cannot prompt syntax errors` do you mean that you have no syntax highlighting or that you don't get compiler warning and errors appearing as you edit the code (i.e. red/yellow underlines on the code)?

**Comment by kanej** [comment]
Closing as we would need more information to progress this issue.

**Comment by bit23665** [comment]
meet the same question

**Comment by kanej** [comment]
> 

@bit23665 can I confirm, are you not seeing syntax highlighting or that you don't get compiler warning and errors appearing as you edit the code?

**Comment by zhangfy1994** [comment]
> > 
> 
> @bit23665 can I confirm, are you not seeing syntax highlighting or that you don't get compiler warning and errors appearing as you edit the code?

yes, the same question。code formatting is ok。

plugin version: v0.7.1
node version: v14.20.0
OS: mac

**Comment by zhangfy1994** [comment]
my project is init by: npx hardhat。when i open .sol file，here is the tips:

Validation blockedCorrupted lockfile: You installed Hardhat with a corrupted lockfile due to the NPM bug #4828. Please delete your node_modules, package-lock.json, reinstall your project, and try again.. Some versions of NPM are affected [by a bug](https://github.com/npm/cli/issues/4828) that leads to corrupt lockfiles being generated. This bug can only affect you if you, or someone at your team, installed the project without a lockfile, but with an existing node_modules. To avoid it, please delete both your node_modules and package-lock.json, and reinstall your project. Note that you don't need to do this every time you install a new dependency, but please make sure to delete your node_modules every time you delete your package-lock.json.

**Comment by zhangfy1994** [comment]
> > 
> 
> @bit23665 can I confirm, are you not seeing syntax highlighting or that you don't get compiler warning and errors appearing as you edit the code?

because my project default folder is 'src', if .sol file out of src, the plugin dose not work.

**Comment by wenjoy** [comment]
Turns out if you specify solidity version ambiguous, you got this error. 
I really think this scenario deserves a better error message.
