### ISSUE TITLE
Symbol are not supported in neovim

### ISSUE THREAD

**Issue by Ethnical** [NomicFoundation/hardhat-vscode#596]
In a normal solidity file we would like to have the symbols working (really useful with telescope). However, got issue because seems not be supported for now: 
 

**Expected Results**:
I took a codebase with golang code just as an example, how what is expected when symbols for LSP are showing up: 

https://github.com/user-attachments/assets/c7b68a27-ca37-4d73-97be-636123198c8d

The cmd to reproduce is: 

```bash
Telescope lsp_document_symbols
```

**Produced Results**:
This is a video on solidity files for example no symbol will appear: 

https://github.com/user-attachments/assets/c88c764c-efcc-4c5a-b55a-b43e5011c2be

This command will produce: 
```bash
[telescope.builtin.lsp_*]: server does not support textDocument/documentSymbol
```

**Comment by kanej** [comment]
Our `documentSymbol` support is currently behind a feature flag. We are rolling out full support over the next few weeks.

**Comment by Ethnical** [comment]
Oh thanks!
Do you have the flag to help to test before released haha?
Would love to make feedback about it!

**Comment by Ethnical** [comment]
Okay seems to be located in this on https://github.com/NomicFoundation/hardhat-vscode/pull/550

**Comment by fvictorio** [comment]
@Ethnical did you get this working with Telescope? We might need to do something extra to enable it, because even after upgrading the LSP server with `:LspInstall solidity_ls_nomicfoundation` I still can't get them to work.

**Comment by Ethnical** [comment]
@fvictorio I didn't tried yet! will try maybe this weekend!

**Comment by fvictorio** [comment]
Ok, found the issue on my side.

The symbols provider is behind a feature flag, which uses the machine id to enable it for some percentage of users. The latest version sets that percentage to 100%, so in practice it's not a feature flag anymore, but it still goes through that mechanism. This means that if the machine id is not available, then all features that are behind flags will be disabled.

For some neovim-configuration-hell reason in my setup, the solidity server doesn't receive a machine id, so it just disables symbols and semantic highlighting. The fix is to add `init_options` in... some place. In my case it's something like this (I'm using [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim)):

```lua
local lsp = require('lsp-zero').preset({})

local lspconfig = require("lspconfig")
local configs = require("lspconfig.configs")

-- ...

configs.solidity = {
  default_config = {
    cmd = {'nomicfoundation-solidity-language-server', '--stdio'},
    filetypes = { 'solidity' },
    root_dir = lspconfig.util.find_git_ancestor,
    single_file_support = true,
  },
}

lspconfig.solidity.setup {
  init_options  = {
    machineId = "machineId"
  }
}
```

I added those `init_options` in `lspconfig.solidity.setup` with an arbitrary value for the machine id, and it started working.

@kanej @OmarTawfik since we are setting this to 100% now and we are unlikely to set it back to a non-100% value, should we just change this so that they are always enabled without going through `isFeatureEnabled`?

**Comment by OmarTawfik** [comment]
> @kanej @OmarTawfik since we are setting this to 100% now and we are unlikely to set it back to a non-100% value, should we just change this so that they are always enabled without going through isFeatureEnabled?

Thank you for the investigation. That would be the next step, yes, given that there are no issues/regressions found so far, and it has been rolled out to %100 for two weeks already (#597).
